name: Docker publish

on:
  push:
    paths:
      - .gitmodules
      - Makefile
    branches:
      - 'master'

jobs:
  docker-image:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        component:
          - agent
          - all-in-one
          - anonymizer
          - collector
          - query
          - ingester
          - tracegen

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host

      - uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Publish images
        run: |
          make dep
          make buildx COMPONENT=${{ matrix.component }}