name: Docker publish images

on:
  push:
    paths:
      - .gitmodules
      - .github/workflows/docker-publish-images.yml
    branches:
      - 'master'

jobs:
  docker-base-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component:
          - baseimg
          - debugimg

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host

      - uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - run: make dep
      - run: make dockerx COMPONENT=${{ matrix.component }}

  docker-image:
    needs:
      - docker-base-image

    runs-on: ubuntu-latest

    strategy:
      matrix:
        component:
          - all-in-one
          - all-in-one-debug
          - agent
          - agent-debug
          - collector
          - collector-debug
          - query
          - query-debug
          - ingester
          - ingester-debug
          - tracegen

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15'
      - uses: actions/setup-node@v2
        with:
          node-version: '^14'

      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host

      - uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - run: make dep
      - run: make dockerx COMPONENT=${{ matrix.component }}