name: Docker publish plugin images

on:
  push:
    paths:
      - .gitmodules
      - .github/workflows/docker-publish-plugin-images.yml
      - Makefile
    branches:
      - 'master'

jobs:
  docker-image:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        component:
          - cassandra-schema
          - es-index-cleaner

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: docker/setup-qemu-action@v1.1.0
      - uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host

      - uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - run: make dep
      - run: make dockerx COMPONENT=${{ matrix.component }}